name: clinica_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.0.2
  rflutter_alert: ^2.0.7
  intl: ^0.20.2
  go_router: ^16.2.2
  table_calendar: ^3.2.0
  calendar_view: ^1.4.0
  syncfusion_flutter_calendar: ^31.1.21
  syncfusion_localizations: ^31.1.22
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/img/
    - assets/icon/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#2196f3"

  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/icon/icon.png"
